[package]
edition = "2021"
name    = "domparser_napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
domparser = { path = "../domparser" }

# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi        = { version = "3.0.0", default-features = false, features = ["napi4"] }
napi-derive = "3.0.0"

[target.'cfg(not(target_env = "musl"))'.dependencies]
mimalloc = { version = "0.1" }

[build-dependencies]
napi-build = "2.1.4"
